---
# tasks file for skeleton

- name: add OS specific variables
  include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ distribution }}-{{ distribution_version }}.yml'
        - '{{ distribution }}-{{ distribution_major_version }}.yml'
        - '{{ distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - '{{ ansible_system }}.yml'
        - 'defaults.yml'
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars
  vars:
    distribution: '{{ ansible_distribution }}'
    distribution_version: '{{ ansible_distribution_version }}'
    distribution_major_version: '{{ ansible_distribution_major_version }}'
  tags:
    - configuration
    - packages

- name: Ensure restic directories exist
  file:
    state: 'directory'
    path: '{{ item }}'
    mode: '0755'
    owner: '{{ restic_dir_owner }}'
    group: '{{ restic_dir_group }}'
  with_items: '{{ restic_create_paths }}'

- name: Install restic
  include: 'install.yml'

- name: include distribution tasks
  include_tasks: '{{ loop_distribution }}'
  with_first_found:
    - files:
        - '{{ distribution }}-{{ distribution_version }}.yml'
        - '{{ distribution }}-{{ distribution_major_version }}.yml'
        - '{{ distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - '{{ ansible_system }}.yml'
        - 'defaults.yml'
      paths:
        - 'distribution'
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: '{{ ansible_distribution }}'
    distribution_version: '{{ ansible_distribution_version }}'
    distribution_major_version: '{{ ansible_distribution_major_version }}'
  tags:
    - configuration
    - packages
