---
- name: Stat test access file
  stat:
    path: ~/restic/access-test.sh
  register: test_file
- name: Check that the test access file exists
  assert:
    that:
      - test_file.stat.exists

- name: Stat test_stdin access file
  stat:
    path: ~/restic/access-test_stdin.sh
  register: test_stdin_file
- name: Check that the test_stdin access file exists
  assert:
    that:
      - test_stdin_file.stat.exists
